### ISSUE TITLE
KY senate is incorrect (as displayed on July 22)

### ISSUE THREAD

**Issue by chrisbrandow** [Princeton-Election-Consortium/data-backend#9]
I assume this is a known issue, but KY is shown on PEC as a tie. That does not match the underlying data.

<img width="205" alt="image" src="https://user-images.githubusercontent.com/4108083/88204125-b6ab4c80-cbff-11ea-8449-389858bfccf8.png">

<img width="460" alt="image" src="https://user-images.githubusercontent.com/4108083/88204267-e4909100-cbff-11ea-8bd3-c43a14ff3ef9.png">

**Comment by mike-iezzi** [comment]
Thank you for bringing this to attention; It is always appreciated when users of our site notify us of potential issues.  You should notice that KY is now McConnell +4 in the table--the median of the three most recent polls.  We had been aware of this issue, and working on it.  Let us know if you notice anything else. 

Thank you!
